name: Wakatime

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          COMMIT_MESSAGE: ":development: update wakatime"
          COMMITTER_NAME: "melodyxpot"
          COMMITTER_EMAIL: "melodyxpot@gmail.com"
          AUTHOR_NAME: "melodyxpot"
          AUTHOR_EMAIL: "melodyxpot@gmail.com"
